/*
  FILE: chat_screen.dart
  DESCRIPTION:
  The central screen for user interaction.
  Allows citizens to enter their inquiries (e.g., "How do I register a residence?").
  Displays the loading state while processing and finally renders the system's answer generated by the LLM.
  
  COMPONENTS:
  - MessageList: Displays the scrollable chat history.
  - InputField: Text input area for new questions.
*/
import 'package:flutter/material.dart';
import 'package:frontend/features/chat/widgets/chat_bubble.dart';

class ChatScreen extends StatefulWidget {
  const ChatScreen({super.key});

  @override
  State<ChatScreen> createState() => _ChatScreenState();
}

class _ChatScreenState extends State<ChatScreen> {
  final TextEditingController _controller = TextEditingController();

  // Ekranda görünecek mesaj listesi (Şimdilik sahte veriler)
  final List<Map<String, dynamic>> _messages = [
    {
      "text": "Hallo! Ich bin GovPilot. Wie kann ich dir helfen?",
      "isMe": false,
    },
  ];

  // Mesaj gönderme fonksiyonu
  void _sendMessage() {
    if (_controller.text.isEmpty) return;

    // 1. Benim mesajımı listeye ekle
    setState(() {
      _messages.add({"text": _controller.text, "isMe": true});
    });

    String userText = _controller.text;
    _controller.clear(); // Yazı kutusunu temizle

    // 2. Botun sahte cevap vermesi (1 saniye sonra)
    Future.delayed(const Duration(seconds: 1), () {
      setState(() {
        _messages.add({
          "text":
              "Das ist eine Antwort auf: '$userText'. (Backend noch nicht verbunden)",
          "isMe": false,
        });
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("GovPilot Bremen"),
        centerTitle: true,
        backgroundColor: Theme.of(context).primaryColor,
        foregroundColor: Colors.white,
      ),
      body: Column(
        children: [
          // MESAJ LİSTESİ ALANI
          Expanded(
            child: ListView.builder(
              padding: const EdgeInsets.all(10),
              itemCount: _messages.length,
              itemBuilder: (context, index) {
                return ChatBubble(
                  message: _messages[index]['text'],
                  isMe: _messages[index]['isMe'],
                );
              },
            ),
          ),

          // YAZI YAZMA ALANI (Input Area)
          Container(
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 10),
            color: Colors.white,
            child: Row(
              children: [
                Expanded(
                  child: TextField(
                    controller: _controller,
                    decoration: InputDecoration(
                      hintText: "Schreib etwas...",
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(25),
                      ),
                      contentPadding: const EdgeInsets.symmetric(
                        horizontal: 20,
                      ),
                    ),
                    onSubmitted: (_) =>
                        _sendMessage(), // Enter'a basınca gönder
                  ),
                ),
                const SizedBox(width: 10),
                FloatingActionButton(
                  onPressed: _sendMessage,
                  backgroundColor: Theme.of(context).primaryColor,
                  mini: true,
                  child: const Icon(
                    Icons.send,
                    color: Colors.white,
                  ), // Küçük buton olsun
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }
}
